### ISSUE TITLE
Metamod Install Directory [BUILD ERROR]

### ISSUE THREAD

**Issue by alerad** [Source2ZE/CS2Fixes#109]
Heyo, I've downloaded Metamod as per usual, and configured the env var as following:

export MMSOURCE112=/home/myuser/workspace/CS2Fixes/build/addons/metamod

Yet I get the following error when it tries to build:

```Traceback (most recent call last):
  File "/home/alerad/.local/lib/python3.10/site-packages/ambuild2/frontend/v2_2/prep.py", line 156, in Configure
    if not cm.generate(options.generator):
  File "/home/alerad/.local/lib/python3.10/site-packages/ambuild2/frontend/context_manager.py", line 93, in generate
    self.parseBuildScripts()
  File "/home/alerad/.local/lib/python3.10/site-packages/ambuild2/frontend/v2_2/context_manager.py", line 50, in parseBuildScripts
    self.execContext(cx)
  File "/home/alerad/.local/lib/python3.10/site-packages/ambuild2/frontend/v2_2/context_manager.py", line 148, in execContext
    exec(code, scriptGlobals)
  File "/home/alerad/workspace/CS2Fixes/AMBuildScript", line 523, in <module>
    MMSPlugin.detectSDKs()
  File "/home/alerad/workspace/CS2Fixes/AMBuildScript", line 203, in detectSDKs
    raise Exception('Could not find a source copy of Metamod:Source')
Exception: Could not find a source copy of Metamod:Source
Configure failed: Could not find a source copy of Metamod:Source```

**Comment by alerad** [comment]
Nevermind, I put addons inside a "metamod" folder and did 

export MMSOURCE112=/home/myuser/workspace/CS2Fixes/build/metamod
